name: CI - Build & Push to ECR + Terraform Deploy

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: tm-app
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::491065739552:role/GitHubActionsECRRole
          role-session-name: GitHubOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Test AWS credentials
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t "$ECR_REPOSITORY:$IMAGE_TAG" ./app

      - name: Tag image
        run: |
          echo "REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
          docker tag "$ECR_REPOSITORY:$IMAGE_TAG" "$REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}

      - name: Push image
        run: docker push "$REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      TF_VAR_image_tag: ${{ env.IMAGE_TAG }}   # <-- this feeds Terraform var
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::491065739552:role/GitHubActionsECRRole
          role-session-name: GitHubOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init/Plan/Apply
        working-directory: infra
        run: |
          terraform init -input=false
          terraform plan -input=false -out=tfplan
          terraform apply -auto-approve tfplan
